config/routes.rb
Rails.application.routes.draw do

	resources :articles
	
	root 'sessions#index'

	post 'signup', to: 'users#create'

	get 'text', to: 'texts#index'

	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	post 'upload', to: 'articles#create'

	post 'filter', to: 'texts#index'

	get 'card', to: 'cards#index'

	post 'createcard', to: 'cards#create'

	post 'reschedule_good', to: 'cards#reschedule_good'
	post 'reschedule_again', to: 'cards#reschedule_again'
	post 'mastered', to: 'cards#set_mastered'
	post 'delete_card', to: 'cards#delete_card'

	post 'delete-last-card', to: 'cards#delete_last_card'

	get 'account', to: 'users#account'
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

	def index
		if params[:difficulty] != nil && params[:language] != nil
			difficulty = params[:difficulty]
			language = params[:language]
		else 
			difficulty = 1
			language = "english"
		end

		@articles = Article.where(difficulty: difficulty, language: language)



		@message = "We currently don't have any <b>" + difficulty_to_string(difficulty) + "</b> articles in <b>" + language.capitalize + "</b>"
		if @articles.count > 0
			@message = "We found <b>" + @articles.count.to_s + " " + difficulty_to_string(difficulty) + "</b> articles in <b>" + language.capitalize + "</b>"
		end

	end

end

app/views/texts/index.html.erb
<div class="container">

	<h1 id="main-title-page" align="center">📕 Browse all articles</h1>


	<div class="choose-text">
		<%= form_for(:article, html: {role: "form", id: "search-article-form"}, url: filter_path) do |f| %>

		
		<%= label_tag(:language, "🌎 Language" , class: "filter-article-label") %>
		<%= select_tag(:language, raw('
			<option value="spanish">🇪🇸 Spanish</option>
			<option value="french">🇫🇷 French</option>
			<option value="korean">🇰🇷 Korean</option>
			<option value="german">🇩🇪 German</option>
			<option value="italian">🇮🇹 Italian</option>
			<option value="russian">🇷🇺 Russian</option>
			<option value="portuguese">🇵🇹 Portuguese</option>
			<option value="hindi">🇮🇳 Hindi</option>
			<option value="dutch">🇳🇱 Dutch</option>
			<option value="turkish">🇹🇷 Turkish</option>
			<option value="polish">🇵🇱 Polish</option>
			'), class: "form-control filter-articles") %>


			<%= label_tag(:difficulty, "💪 Difficulty", class: "filter-article-label") %>
			<%= select_tag(:difficulty, raw('
				<option value="1">😁 Beginner</option>
				<option value="2">🏃‍♂️ Upper Beginner</option>
				<option value="3">👨‍🎓 Intermediate</option>
				<option value="4">🏋️‍♂️ Upper Intermediate</option>
				<option value="5">🔥 Advanced</option>
				'), class: "form-control filter-articles") %>


				<%= f.button "Search", class: "btn btn-primary miner-button full-width" %>


				<% end %>
			</div>

			<p align="center" class="search-results">
				<% 

				def difficulty_to_string(difficulty_int)
					case difficulty_int
					when 1
						return "beginner"
					when 2
						return "upper beginner"
					when 3
						return "intermediate"
					when 4
						return "upper intermediate"
					when 5
						return "advanced"
					else
						return difficulty_int.to_s
					end
				end 

				%>

				<% if @articles.count == 0 %>

				No articles at the moment 🤷‍♀️. 
				<a href="#" class="link-miner" data-toggle="modal" data-target="#uploadArticleModal">
						Create one now.
					</a>

				<% else %>

				🔍 We found <%= @articles.count %> <b class="highlighted"><%= difficulty_to_string(@articles.first.difficulty) %></b> articles in <b class="highlighted"><%= @articles.first.language.capitalize %></b>

				<% end %>
			</p>
			<%= render @articles %>



		</div>