config/routes.rb
Rails.application.routes.draw do

	resources :articles
	
	root 'sessions#index'

	post 'signup', to: 'users#create'

	get 'text', to: 'texts#index'

	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	post 'upload', to: 'articles#create'

	post 'filter', to: 'texts#index'

	get 'card', to: 'cards#index'

	post 'createcard', to: 'cards#create'

	post 'reschedule_good', to: 'cards#reschedule_good'
	post 'reschedule_again', to: 'cards#reschedule_again'
	post 'mastered', to: 'cards#set_mastered'
	post 'delete_card', to: 'cards#delete_card'

	post 'delete-last-card', to: 'cards#delete_last_card'

	get 'account', to: 'users#account'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			🚀 Developed by Lois Lin
		</div>
	</div>	
</footer>

app/views/layouts/_header.html.erb
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-dark">
		<a id="polyglot-lab-logo" class="navbar-brand" href="/">
			<div>
				polyglot <span style="font-family: pacifico">lab</span>
			</div>
		</a>
		<button class="navbar-toggler" type="button" data-toggle="modal" data-target="#navigationModal">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="modal fade" id="navigationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-xl" role="document">
				<div class="modal-content">

					<div id="nav-modal-body" class="modal-body">

						<% if logged_in? %>

						<%= link_to "Articles", text_path, class: "modal-nav-item" %>
						<br>
						<!-- Button trigger modal -->
						<a href="#" class="modal-nav-item" data-toggle="modal" data-target="#uploadArticleModal">
							Upload article
						</a>
						<br>
						<%= link_to "SRS", card_path, class: "modal-nav-item" %>
						<br>
						<%= link_to "Account", account_path, class: "modal-nav-item" %>
						<br>
						<%= link_to "Logout", logout_path, method: :delete, class: "modal-nav-item" %>
						<br>
						<% else %>
						<a onclick="toggleModal()" href="#" class="modal-nav-item" data-toggle="modal" data-target="#loginModal">Log in</a>
						<% end %>

					</div>
				</div>

			</div>
		</div>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto">

				<% if logged_in? %>

				<%= link_to "Articles", text_path, class: "nav-link" %>

				<!-- Button trigger modal -->
				<a href="#" class="nav-link nav-miner" data-toggle="modal" data-target="#uploadArticleModal">
					Upload article
				</a>

				<%= link_to "SRS", card_path, class: "nav-link" %>
				<%= link_to "Account", account_path, class: "nav-link" %>
				<%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
				<% else %>
				<a href="#" class="nav-link" data-toggle="modal" data-target="#loginModal">Log in</a>
				<% end %>
			</ul>
		</div>
	</nav>

</div>

<%= render 'layouts/upload' %>

app/views/layouts/_login.html.erb
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div id="login-modal-content" class="modal-content">

			<div class="modal-body">

				<div align="center" class="title-modal">🎉 Log in</div>

				<%= form_for(:session, html: {class: "", role: "form", id: "loginFormRoot"}, url: login_path) do |f| %>
				<div class="field">
					<%= f.text_field :email, placeholder: "Username", class: "form-control" %>
				</div>
				<div class="field">
					<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
				</div>
				<%= f.button "Log in", class: "btn btn-primary miner-button full-width" %>

				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/layouts/_subscription.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">

            <div id="col-subscription" class="col-md-6">
              <h2 id="title-modal" align="center">Start learning 🚀</h2>

              <%= form_for(:user, html: {role: "form", id: "homepage-signup"}, url: signup_path) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>


                <%= f.password_field :password, placeholder: "Choose a password" , class: "form-control" %>

                <%= f.button "Start learning", class: "btn btn-primary miner-button full-width" %>
                
              </div>
              <% end %>              
            </div>

                <div class="col-md-6">
              <p>
                💸 <b class="highlighted">A free alternative</b> to Lingq
              </p>
              <p>
                🗂 <b class="highlighted">SRS</b> to help you remember words / phrases
              </p>
              <p>
                📓 <b class="highlighted">A text reader</b> to help you with difficult vocab
              </p>
              <p>
                🎧 <b class="highlighted">Listen to the pronunciation</b> (using machine learning)
              </p>
                  <p id="conditions-subscription">By clicking this button you accept our <a target="_blank" href="https://www.termsandconditionsgenerator.com/live.php?token=3WlCJqTEHuWNADR73bWmdBTSOwR55062">Terms of Service</a> and <a target="_blank" href="https://www.gdprprivacypolicy.net/live.php?token=exTMfUCMxoh8rbgHwxAdXFmDabmBEt9v">Privacy Policy</a>. We will not share your data with third parties and you will only receive newsletters and notifications from polyglot lab.</p>
            </div>

          </div>
 
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_upload.html.erb
<div class="modal fade" id="uploadArticleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <div align="center" class="title-modal">Import an article 📗</div>
        <%= form_for(:article, html: {role: "form", id: "upload-modal-form"}, url: upload_path) do |f| %>
        <div class="form-group">
          


          <div class="container-fluid">
            <div class="row">
              <div id="title-upload" class="col-md-6">
          

              <%= hidden_field_tag(:user, current_user) %>


                <%= f.text_field :title, placeholder: "Title of the article", class: "form-control" %>
              </div>

              <div class="col-md-3">
               <!-- Change the hidden field depending on the dropdown that follows -->
              <%= select_tag(:language, raw('
                <option value="spanish">🇪🇸 Spanish</option>
                <option value="french">🇫🇷 French</option>
                <option value="korean">🇰🇷 Korean</option>
                <option value="german">🇩🇪 German</option>
                <option value="italian">🇮🇹 Italian</option>
                <option value="russian">🇷🇺 Russian</option>
                <option value="portuguese">🇵🇹 Portuguese</option>
                <option value="hindi">🇮🇳 Hindi</option>
                <option value="dutch">🇳🇱 Dutch</option>
                <option value="turkish">🇹🇷 Turkish</option>
                <option value="polish">🇵🇱 Polish</option>
              '), class: "form-control",) %>
              </div>

              <div class="col-md-3">
               <!-- Change the hidden field depending on the dropdown that follows -->
				<%= select_tag(:difficulty, raw('
                <option value="1">😁 Beginner</option>
                <option value="2">🏃‍♂️ Upper Beginner</option>
                <option value="3">👨‍🎓 Intermediate</option>
                <option value="4">🏋️‍♂️ Upper Intermediate</option>
                <option value="5">🔥 Advanced</option>
              '), class: "form-control",) %>
              </div>

          </div>
        </div>
        
              
        <%= f.text_area :lesson, placeholder: "Paste the article here" , class: "form-control", id: "article-textarea" %>

        <%= f.button "Upload", class: "btn btn-primary miner-button full-width" %>

      </div>
      <% end %>
    </div>

  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Polyglot Lab</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<%= favicon_link_tag asset_path('favicon.png') %>

	 <meta charset="UTF-8">

</head>

<body>

	<%= render 'layouts/header' %>

	<div id="flash-messages" class="container">
		<% flash.each do |type, msg| %>
		<div class="alert alert-info">
			<%= msg %>
		</div>
		<% end %>
	</div>

	<%= yield %>

	

	<%= render 'layouts/footer' %>

</body>
</html>